-- 코드를 작성해주세요
SELECT ED1.ID, IFNULL(ED2.CHD, 0) AS CHILD_COUNT
FROM ECOLI_DATA ED1 LEFT OUTER JOIN (
    SELECT PARENT_ID, COUNT(*) AS CHD
    FROM ECOLI_DATA
    GROUP BY PARENT_ID
) ED2
ON ED1.ID = ED2.PARENT_ID
ORDER BY ED1.ID ASC