WITH TOTAL_COUNT AS (
    SELECT COUNT(*) AS COUNTS
    FROM ECOLI_DATA
), 
RANKS AS (
    SELECT ID, RANK() OVER(ORDER BY SIZE_OF_COLONY DESC) AS RANK_NUMBER
    FROM ECOLI_DATA
)

SELECT R.ID,
CASE
    WHEN R.RANK_NUMBER <= TC.COUNTS * 0.25 THEN 'CRITICAL'
    WHEN R.RANK_NUMBER <= TC.COUNTS * 0.5 THEN 'HIGH'
    WHEN R.RANK_NUMBER <= TC.COUNTS * 0.75 THEN 'MEDIUM'
    ELSE 'LOW'
END AS COLONY_NAME
FROM RANKS R, TOTAL_COUNT TC
ORDER BY R.ID;
