WITH 
MAX_REVIEW_USER AS (
    SELECT DISTINCT MEMBER_ID, COUNT(*) AS REVIEW_COUNT
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY REVIEW_COUNT DESC
    LIMIT 1
)

SELECT MP.MEMBER_NAME, RR.REVIEW_TEXT, DATE_FORMAT(RR.REVIEW_DATE, '%Y-%m-%d')
FROM MEMBER_PROFILE AS MP JOIN REST_REVIEW AS RR
ON MP.MEMBER_ID = RR.MEMBER_ID
JOIN MAX_REVIEW_USER AS MRU
ON MP.MEMBER_ID = MRU.MEMBER_ID
ORDER BY RR.REVIEW_DATE ASC, RR.REVIEW_TEXT ASC
